		<tr>
			<th colspan="4" class="title">审计报告</th>
		</tr>
		@if(empty($sj1))
		<tr>
			<th rowspan="4">
				@if($sj1->ywwftg == '1')
					业务无法提供
				@else
					财务报表日期<br>
					{{$sj1->year}}
				@endif
			</th>
			<th>资产总额(万元)</th>
			<th>负债总额(万元)</th>
			<th>净资产(所有者权益)(万元</th>
		</tr>
		<tr>
			<td>{{$sj1->zzc}}</td>
			<td>{{$sj1->zfz}}</td>
			<td>{{$sj1->syzqy}}</td>
		</tr>
		<tr>
			<th>营业收入(万元)</th>
			<th>利润总额(万元)</th>
			<th>净利润(万元)</th>
		</tr>
		<tr>
			<td>{{$sj1->yysl}}</td>
			<td>{{$sj1->yylr}}</td>
			<td>{{$sj1->jlr}}</td>
		</tr>
		@endif
		@if(empty($sj2))
		<tr>
			<th rowspan="4">
				@if($sj2->ywwftg == '1')
					业务无法提供
				@else
					财务报表日期<br>
					{{$sj2->year}}
				@endif
			</th>
			<th>资产总额(万元)</th>
			<th>负债总额(万元)</th>
			<th>净资产(所有者权益)(万元</th>
		</tr>
		<tr>
			<td>{{$sj2->zzc}}</td>
			<td>{{$sj2->zfz}}</td>
			<td>{{$sj2->syzqy}}</td>
		</tr>
		<tr>
			<th>营业收入(万元)</th>
			<th>利润总额(万元)</th>
			<th>净利润(万元)</th>
		</tr>
		<tr>
			<td>{{$sj2->yysl}}</td>
			<td>{{$sj2->yylr}}</td>
			<td>{{$sj2->jlr}}</td>
		</tr>
		@endif
		@if(empty($sj3))
		<tr>
			<th rowspan="4">
				@if($sj3->ywwftg == '1')
					业务无法提供
				@else
					财务报表日期<br>
					{{$sj3->year}}
				@endif
			</th>
			<th>资产总额(万元)</th>
			<th>负债总额(万元)</th>
			<th>净资产(所有者权益)(万元</th>
		</tr>
		<tr>
			<td>{{$sj3->zzc}}</td>
			<td>{{$sj3->zfz}}</td>
			<td>{{$sj3->syzqy}}</td>
		</tr>
		<tr>
			<th>营业收入(万元)</th>
			<th>利润总额(万元)</th>
			<th>净利润(万元)</th>
		</tr>
		<tr>
			<td>{{$sj3->yysl}}</td>
			<td>{{$sj3->yylr}}</td>
			<td>{{$sj3->jlr}}</td>
		</tr>
		@endif